FROM zuohuadong/caddy:alpine

ARG plugins="cors"

## ARG plugins="cors cgi cloudflare azure linode"

RUN caddyplug install ${plugins}

EXPOSE 80 443 2015

WORKDIR /var/www/mtb/mtb-cms-backend/public

CMD ["/usr/bin/caddy", "-conf", "/etc/Caddyfile"]
